services:
  db:
    image: mariadb:10.9
    container_name: igreja_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: igreja_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL="mysql+mysqlconnector://user:password@db/igreja_db"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./front
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db_data:
