version: '3.8'

services:
  db:
    image: mariadb
    container_name: igreja_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: igreja_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+mysqlconnector://user:password@igreja_db:3306/igreja_db"
    env_file:
      - .env
    networks:
      - app-network
  frontend:
    build:
      context: ./front
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: