services:
  backend:
    build:
      context: ./back
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - app-network
  frontend:
    build:
      context: ./front
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend
  db:
    image: mariadb:10.9
    container_name: igreja-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: igreja_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
